
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-k8s-device-plugin
spec:
  selector:
    matchLabels:
      name: sample-k8s-device-plugin
  template:
    metadata:
      labels:
        name: sample-k8s-device-plugin
    spec:
      containers:
        - name: sample-k8s-device-plugin
          image: leonharetd/sample-k8s-device-plugin:dev
          imagePullPolicy: Always
          volumeMounts:
            - name: device-plugins
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins