apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-1
  labels:
    name: busybox-sleep
spec:
  containers:
  - name: busybox-sleep-1
    image: busybox
    args:
      - "sleep"
      - "infinity"
    resources:
      limits:
        hardware-vendor.example/suger: 2



